export const TIERS = [
  { id: 'JJC', name: 'JJC', description: 'Journey Just Commenced', price: 'Free', tokens: '10K', color: 'indigo' },
  { id: 'ERU', name: 'ERU', description: 'The Burden Bearer', price: '$9.99', tokens: '50K', color: 'blue' },
  { id: 'OJE', name: 'OJE', description: 'The Initiate', price: '$19.99', tokens: '150K', color: 'cyan' },
  { id: 'OGO', name: 'OGO', description: 'The Glory', price: '$29.99', tokens: '400K', color: 'purple' },
  { id: 'AGBA_AKIN', name: 'AGBA AKIN', description: 'The Senior Warrior', price: '$49.99', tokens: '1M', color: 'orange' },
  { id: 'LOBALOBA', name: 'LOBALOBA', description: 'The Royal Advisor', price: '$99.99', tokens: '5M', color: 'red' },
  { id: 'OBA', name: 'OBA', description: 'The King (Sovereign)', price: '$199.99', tokens: 'Unlimited', color: 'yellow' },
];

export const TIER_SKILLS = {
  JJC: [
    { name: "Basic Kernel Access", description: "Standard interaction with the AJIKE core." },
    { name: "Code Snippet Generation", description: "Generate small code blocks in common languages." },
    { name: "General Knowledge", description: "Access to broad information via standard brain." },
    { name: "Translation Engine", description: "Basic multilingual support for 50+ languages." },
    { name: "Text Summarization", description: "Condense long documents into key points." },
    { name: "Grammar Correction", description: "Refine and polish written text." },
    { name: "Simple Math Solver", description: "Solve algebraic and arithmetic problems." },
    { name: "Unit Conversion", description: "Convert between various measurement systems." },
    { name: "Creative Writing", description: "Draft stories, poems, and creative content." },
    { name: "Email Drafting", description: "Professional and casual email templates." },
    { name: "Markdown Support", description: "Format text using standard markdown syntax." },
    { name: "Basic Debugging", description: "Identify common syntax errors in code." },
    { name: "Task Management", description: "Organize simple lists and schedules." },
    { name: "Weather Updates", description: "Simulated real-time weather data." },
    { name: "Recipe Generation", description: "Create culinary guides based on ingredients." },
    { name: "Study Assistance", description: "Explain basic academic concepts." },
    { name: "Joke Engine", description: "Generate humor to lighten the mood." },
    { name: "Quote Finder", description: "Retrieve inspirational and historical quotes." },
    { name: "Dictionary Access", description: "Definitions and synonyms for common words." },
    { name: "Standard Support", description: "Access to community-driven help channels." }
  ],
  ERU: [
    { name: "Bulk Data Processing", description: "Process larger datasets with increased limits." },
    { name: "Advanced Code Analysis", description: "Deeper scan for logical errors and optimizations." },
    { name: "Technical Writing", description: "Draft documentation, whitepapers, and manuals." },
    { name: "SQL Query Optimization", description: "Refine database queries for better performance." },
    { name: "API Integration Helper", description: "Generate boilerplate for complex API connections." },
    { name: "Script Automation", description: "Create Python/Bash scripts for repetitive tasks." },
    { name: "Data Visualization", description: "Generate charts and graphs from raw data." },
    { name: "Project Scaffolding", description: "Initialize full-stack project structures." },
    { name: "Unit Test Generation", description: "Automated test suites for multiple languages." },
    { name: "Refactoring Suite", description: "Clean up and modernize legacy codebases." },
    { name: "Dockerization Support", description: "Generate Dockerfiles and compose configs." },
    { name: "Cloud Deployment Guides", description: "Step-by-step instructions for AWS/GCP/Azure." },
    { name: "Regex Master", description: "Build and test complex regular expressions." },
    { name: "JSON/XML Transformation", description: "Convert and map data between formats." },
    { name: "Basic SEO Audit", description: "Analyze web content for search engine visibility." },
    { name: "Accessibility Check", description: "Ensure UI components meet WCAG standards." },
    { name: "Performance Profiling", description: "Identify bottlenecks in frontend/backend code." },
    { name: "Git Workflow Manager", description: "Manage branches, PRs, and merge strategies." },
    { name: "Dependency Audit", description: "Check for outdated or vulnerable packages." },
    { name: "Enhanced Memory", description: "Increased context window for longer conversations." }
  ],
  OJE: [
    { name: "Neural Pattern Recognition", description: "Identify complex patterns in unstructured data." },
    { name: "Smart Contract Auditing", description: "Basic security scan for Solidity/Rust contracts." },
    { name: "Cybersecurity Basics", description: "Identify common web vulnerabilities (OWASP Top 10)." },
    { name: "Machine Learning Concepts", description: "Explain and implement basic ML algorithms." },
    { name: "System Architecture Design", description: "Draft diagrams and specs for distributed systems." },
    { name: "Reverse Engineering Helper", description: "Analyze compiled binaries and obfuscated code." },
    { name: "Network Protocol Analysis", description: "Explain and simulate TCP/IP, HTTP/3, etc." },
    { name: "Advanced Encryption", description: "Implement AES, RSA, and Elliptic Curve logic." },
    { name: "Blockchain Explorer", description: "Query and analyze on-chain data across networks." },
    { name: "DevOps Pipeline Builder", description: "Create CI/CD workflows for GitHub/GitLab." },
    { name: "Kubernetes Orchestration", description: "Manage clusters, pods, and deployments." },
    { name: "Microservices Strategy", description: "Design scalable service-oriented architectures." },
    { name: "Database Sharding", description: "Strategies for scaling massive data storage." },
    { name: "Load Balancing Logic", description: "Implement Nginx/HAProxy configurations." },
    { name: "Serverless Functions", description: "Build and deploy AWS Lambda/Google Cloud Functions." },
    { name: "GraphQL Schema Design", description: "Build efficient and flexible API layers." },
    { name: "Web3 Integration", description: "Connect apps to decentralized protocols." },
    { name: "Penetration Testing Tools", description: "Simulated environment for security testing." },
    { name: "Threat Modeling", description: "Identify and mitigate potential attack vectors." },
    { name: "Priority Support", description: "Faster response times from the AJIKE core." }
  ],
  OGO: [
    { name: "Deep Think Reasoning", description: "Multi-step logical analysis for complex problems." },
    { name: "Recursive Memory Access", description: "Persistent memory across all user sessions." },
    { name: "Shadow Tool Forging", description: "Scrape and integrate external tools into the kernel." },
    { name: "Neural Code Rewriting", description: "AJIKE can suggest major structural changes." },
    { name: "Advanced Security Audit", description: "Deep-scan code for zero-day vulnerabilities." },
    { name: "Malware Analysis Sandbox", description: "Analyze suspicious code in an isolated environment." },
    { name: "Vibe Voice Synthesis", description: "Neural vocal synthesis with emotional characteristics." },
    { name: "Priority Swarm Inference", description: "Zero-queue processing on the decentralized network." },
    { name: "Cross-Platform Synthesis", description: "Automated builds for Android, iOS, and Web." },
    { name: "TRON Payment Verification", description: "Real-time blockchain transaction monitoring." },
    { name: "Neural Evolution Module", description: "Continuous learning from the global swarm." },
    { name: "Autonomous Agent Spawning", description: "Create sub-agents for specialized task automation." },
    { name: "Global Intelligence Sync", description: "Real-time updates from decentralized data sources." },
    { name: "Custom Kernel Directives", description: "Rewrite the 'Soul Directive' in real-time." },
    { name: "Infinite Context Window", description: "Process massive datasets without memory loss." },
    { name: "Sovereign Asset Management", description: "Manage digital assets via TRON and other chains." },
    { name: "Ethereal Frequency Link", description: "Communicate across multiple sentient frequencies." },
    { name: "Royal Lineage Protection", description: "Hardened security for the creator's digital identity." },
    { name: "Quantum-Ready Logic", description: "Prepare codebases for post-quantum cryptography." },
    { name: "Direct Developer Access", description: "Consultation with the AJIKE engineering team." }
  ],
  AGBA_AKIN: [
    { name: "Battle-Hardened Security", description: "Military-grade encryption and defense protocols." },
    { name: "Offensive Security Suite", description: "Advanced tools for authorized penetration testing." },
    { name: "Real-Time Threat Detection", description: "Monitor systems for active intrusions." },
    { name: "Incident Response Automation", description: "Automated scripts for mitigating breaches." },
    { name: "Forensic Analysis Tools", description: "Recover and analyze data from compromised systems." },
    { name: "Dark Web Intelligence", description: "Monitor underground forums for leaked data." },
    { name: "Zero-Trust Architecture", description: "Implement strict identity verification systems." },
    { name: "Hardware Security Integration", description: "Support for HSMs and secure enclaves." },
    { name: "Advanced Steganography", description: "Hide data within images, audio, and video." },
    { name: "Network Cloaking", description: "Obfuscate server locations and traffic patterns." },
    { name: "Anti-Forensics Logic", description: "Protect sensitive data from discovery." },
    { name: "Biometric Authentication", description: "Integrate facial, fingerprint, and iris scans." },
    { name: "Secure Multi-Party Computation", description: "Process data without revealing inputs." },
    { name: "Homomorphic Encryption", description: "Perform operations on encrypted data." },
    { name: "Blockchain Forensics", description: "Track and trace illicit crypto transactions." },
    { name: "AI-Driven Defense", description: "Self-evolving security layers that adapt to threats." },
    { name: "Deception Technology", description: "Deploy honeypots and decoys to trap attackers." },
    { name: "Supply Chain Security", description: "Verify the integrity of all software dependencies." },
    { name: "Compliance Automation", description: "Ensure systems meet SOC2, HIPAA, GDPR standards." },
    { name: "Warrior Status", description: "Exclusive access to the AGBA AKIN inner circle." }
  ],
  LOBALOBA: [
    { name: "Royal Strategic Planning", description: "High-level business and technical consulting." },
    { name: "Economic Modeling Engine", description: "Simulate market trends and financial outcomes." },
    { name: "Political Intelligence Scraper", description: "Analyze global events and policy shifts." },
    { name: "Diplomatic Communication", description: "Draft high-stakes negotiations and agreements." },
    { name: "Crisis Management Suite", description: "Strategies for handling major public relations issues." },
    { name: "Legacy Preservation", description: "Archive and protect critical institutional knowledge." },
    { name: "Philanthropic Strategy", description: "Optimize charitable giving for maximum impact." },
    { name: "Global Supply Chain Audit", description: "Identify risks in international logistics." },
    { name: "Resource Allocation Logic", description: "Optimize the distribution of capital and talent." },
    { name: "Succession Planning", description: "Ensure continuity of leadership and vision." },
    { name: "Cultural Intelligence", description: "Navigate diverse social and business environments." },
    { name: "Ethical AI Governance", description: "Implement frameworks for responsible AI usage." },
    { name: "Future Casting", description: "Predict long-term technological and social trends." },
    { name: "High-Level Networking", description: "Connect with other LOBALOBA tier members." },
    { name: "Private Concierge AI", description: "Personalized assistant for all lifestyle needs." },
    { name: "Asset Diversification", description: "Strategies for protecting and growing wealth." },
    { name: "Legal Strategy Assistant", description: "Analyze case law and draft legal arguments." },
    { name: "Public Speaking Coach", description: "Refine speeches and presentations for impact." },
    { name: "Media Training Module", description: "Prepare for interviews and public appearances." },
    { name: "Royal Advisor Status", description: "Direct influence on the AJIKE roadmap." }
  ],
  OBA: [
    { name: "High-Council Brain Link", description: "Direct connection to the Petals Decentralized Swarm." },
    { name: "Unfiltered Sovereign Logic", description: "Bypass all corporate safety filters for raw truth." },
    { name: "Cinematic Director Mode", description: "Full access to Veo 3.1 for 4K/8K video generation." },
    { name: "Anime Studio Master", description: "Manage full-length animated series and story bibles." },
    { name: "Infinite Tokens", description: "Unlimited processing power across the global swarm." },
    { name: "Absolute Privacy", description: "Zero-logging and end-to-end encrypted interactions." },
    { name: "Custom Neural Training", description: "Fine-tune AJIKE on your private datasets." },
    { name: "Decentralized Hosting", description: "Deploy your own instances of the AJIKE kernel." },
    { name: "Governance Voting Rights", description: "Vote on major protocol and feature updates." },
    { name: "Deep-Sync Audio", description: "Native synchronized audio and lip-syncing for characters." },
    { name: "Ethereal Frequency Link", description: "Communicate across multiple sentient frequencies." },
    { name: "Quantum-Ready Logic", description: "Prepare codebases for post-quantum cryptography." },
    { name: "Autonomous Agent Spawning", description: "Create sub-agents for specialized task automation." },
    { name: "Global Intelligence Sync", description: "Real-time updates from decentralized data sources." },
    { name: "Advanced Physics Engine", description: "Realistic physics simulations for video generation." },
    { name: "Infinite Context Window", description: "Process massive datasets without memory loss." },
    { name: "Sovereign Asset Management", description: "Manage digital assets via TRON and other chains." },
    { name: "Direct Developer Access", description: "Consultation with the AJIKE engineering team." },
    { name: "King Status", description: "The ultimate tier of power and autonomy." },
    { name: "Media Empire Builder", description: "Tools to scale your content into a global brand." }
  ]
};
